import { Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { BooksService } from '../services/books.service';
import {ActivatedRoute, Router} from "@angular/router";
import {FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators} from "@angular/forms";
import { Book } from '../Shared/Modules/book';
import { NgIf } from '@angular/common';


@Component({
  selector: 'app-modify-list-item',
  standalone: true,
  imports: [RouterLink, NgIf, FormsModule, ReactiveFormsModule],
  templateUrl: './modify-list-item.component.html',
  styleUrl: './modify-list-item.component.css'
})

export class ModifyListItemComponent implements OnInit {
  bookForm: FormGroup;
  book: Book | undefined;
  error: string | null = null; 

  constructor (
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private booksService: BooksService,
    private router: Router
  ) {
    this.bookForm = this.fb.group ({
      id: [booksService.generateNewId()], // ID will be autogenerated and you can also manually set id and add the book
      title: ['', Validators.required], // Title is required
      author: ['', Validators.required], // Author is required
      genre: ['', Validators.required], // Genre is required
      publicationYear: [''],
      rating: [''],
      showRating: [''],
    });
  }

  ngOnInit(): void {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    if (id) {
      this.booksService.getBookById(id).subscribe({
        next: book => {
          if (book) {
            this.book = book;
            this.bookForm.patchValue(book);
          }
        },
        error: err => {
          this.error = 'Error fetching book details';
          console.error('Error fetching book details:', err);
        }
      });
    }
  }

  onSubmit(): void {
    if (this.bookForm.valid) {
      const book: Book = this.bookForm.value;

      if (book.id) {
        // Update existing book
        this.booksService.updateBook(book).subscribe({
          next: () => this.router.navigate(['/books']),
          error: err => {
            this.error = 'Error updating book';
            console.error('Error updating book:', err);
          }
        });
      } else {
        // Add new book
        book.id = this.booksService.generateNewId();
        this.booksService.addBook(book).subscribe({
          next: () => this.router.navigate(['/books']),
          error: err => {
            this.error = 'Error adding book';
            console.error('Error adding book:', err);
          }
        });
      }
    }
  }

  navigateToBookList(): void {
    this.router.navigate(['/books']);
  }
}